namespace Clovent.Platform.Printing;

/// <summary>
/// Lifecycle state of an operational print job.
/// Spooler acceptance is distinguished from physical paper delivery confirmation.
/// </summary>
public enum PrinterJobStatus
{
    /// <summary>Job was generated by the POS client or application.</summary>
    Requested = 0,

    /// <summary>Job is buffered in the local processing queue or Transactional Outbox.</summary>
    Queued = 1,

    /// <summary>Job was successfully accepted by the operating system print spooler.</summary>
    Submitted = 2,

    /// <summary>Physical printer hardware acknowledged completion (where bidirectional status is supported).</summary>
    Confirmed = 3,

    /// <summary>Printer error occurred (spooler offline, paper jam, port unreachable).</summary>
    Failed = 4,

    /// <summary>Job was cancelled by an operator prior to submission.</summary>
    Cancelled = 5,

    /// <summary>Job failed primary physical dispatch and is quarantined into durable storage pending recovery.</summary>
    Quarantined = 6
}
