using Clovent.Desktop.Forms.Base.Appearance;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraGrid.Views.Grid;

namespace Clovent.Desktop.Forms.Restaurant.ActivityLog;

partial class ActivityLogView
{
    /// <summary>Required designer variable.</summary>
    private System.ComponentModel.IContainer components = null;

    #region Component Designer generated code

    /// <summary>
    /// Required method for Designer support - do not modify the contents of
    /// this method with the code editor.
    /// </summary>
    /// <remarks>
    /// Every statement here is deliberately restricted to the subset the
    /// Visual Studio WinForms Designer's own code parser can round-trip -
    /// no <see langword="var"/> locals, no lambda/anonymous-method event
    /// handlers (<c>+=</c> targets are always a named method below), no
    /// <c>nameof()</c>, and no chaining a property assignment onto a
    /// method call's return value on the same statement (e.g. never
    /// <c>Foo(...).Width = 1;</c>) - an earlier version of this file used
    /// all four and the Designer refused to open it ("The designer cannot
    /// process the code... generated by the designer and should not be
    /// manually modified"), because every one of those four is valid C#
    /// but outside what the Designer's own serializer understands. Every
    /// control (including each <see cref="GridColumn"/>) is a field for the
    /// same reason real Designer-generated code never uses a local variable
    /// for a component.
    /// </remarks>
    private void InitializeComponent()
    {
        _searchEdit = new TextEdit();
        _refreshButton = new SimpleButton();
        _grid = new GridControl();
        _gridView = new GridView();
        _emptyStateLabel = new LabelControl();
        _gridHost = new PanelControl();
        _toolbar = new FlowLayoutPanel();
        _columnOccurredAtUtc = new GridColumn();
        _columnPerformedBy = new GridColumn();
        _columnMachineName = new GridColumn();
        _columnAction = new GridColumn();
        _columnDetails = new GridColumn();
        ((System.ComponentModel.ISupportInitialize)_searchEdit.Properties).BeginInit();
        ((System.ComponentModel.ISupportInitialize)_grid).BeginInit();
        ((System.ComponentModel.ISupportInitialize)_gridView).BeginInit();
        ((System.ComponentModel.ISupportInitialize)_gridHost).BeginInit();
        _gridHost.SuspendLayout();
        SuspendLayout();
        //
        // _columnOccurredAtUtc
        //
        _columnOccurredAtUtc.Caption = "Date/Time";
        _columnOccurredAtUtc.FieldName = "OccurredAtUtc";
        _columnOccurredAtUtc.Name = "_columnOccurredAtUtc";
        _columnOccurredAtUtc.Visible = true;
        _columnOccurredAtUtc.VisibleIndex = 0;
        _columnOccurredAtUtc.Width = 160;
        //
        // _columnPerformedBy
        //
        _columnPerformedBy.Caption = "User";
        _columnPerformedBy.FieldName = "PerformedBy";
        _columnPerformedBy.Name = "_columnPerformedBy";
        _columnPerformedBy.Visible = true;
        _columnPerformedBy.VisibleIndex = 1;
        _columnPerformedBy.Width = 140;
        //
        // _columnMachineName
        //
        _columnMachineName.Caption = "Machine";
        _columnMachineName.FieldName = "MachineName";
        _columnMachineName.Name = "_columnMachineName";
        _columnMachineName.Visible = true;
        _columnMachineName.VisibleIndex = 2;
        _columnMachineName.Width = 140;
        //
        // _columnAction
        //
        _columnAction.Caption = "Action";
        _columnAction.FieldName = "Action";
        _columnAction.Name = "_columnAction";
        _columnAction.Visible = true;
        _columnAction.VisibleIndex = 3;
        _columnAction.Width = 130;
        //
        // _columnDetails
        //
        _columnDetails.Caption = "Details";
        _columnDetails.FieldName = "Details";
        _columnDetails.Name = "_columnDetails";
        _columnDetails.Visible = true;
        _columnDetails.VisibleIndex = 4;
        //
        // _gridView
        //
        _gridView.Columns.AddRange(new GridColumn[] { _columnOccurredAtUtc, _columnPerformedBy, _columnMachineName, _columnAction, _columnDetails });
        _gridView.GridControl = _grid;
        _gridView.Name = "_gridView";
        _gridView.OptionsBehavior.Editable = false;
        _gridView.OptionsSelection.MultiSelect = false;
        _gridView.OptionsView.ShowGroupPanel = false;
        _gridView.RowHeight = 32;
        _gridView.CustomColumnDisplayText += GridView_CustomColumnDisplayText;
        //
        // _grid
        //
        _grid.Dock = DockStyle.Fill;
        _grid.MainView = _gridView;
        _grid.Name = "_grid";
        _grid.ViewCollection.Add(_gridView);
        //
        // _emptyStateLabel
        //
        _emptyStateLabel.Dock = DockStyle.Fill;
        _emptyStateLabel.Name = "_emptyStateLabel";
        _emptyStateLabel.Text = "No activity recorded yet.";
        _emptyStateLabel.Visible = false;
        //
        // _gridHost
        //
        _gridHost.Controls.Add(_emptyStateLabel);
        _gridHost.Controls.Add(_grid);
        _gridHost.Dock = DockStyle.Fill;
        _gridHost.Name = "_gridHost";
        //
        // _searchEdit
        //
        _searchEdit.Name = "_searchEdit";
        _searchEdit.Properties.NullValuePrompt = "Search action, user, or details...";
        _searchEdit.Width = 280;
        _searchEdit.EditValueChanged += SearchEdit_EditValueChanged;
        //
        // _refreshButton
        //
        _refreshButton.Name = "_refreshButton";
        _refreshButton.Text = "⟳  Refresh";
        _refreshButton.Click += RefreshButton_Click;
        //
        // _toolbar
        //
        _toolbar.AutoSize = true;
        _toolbar.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        _toolbar.Controls.Add(_searchEdit);
        _toolbar.Controls.Add(_refreshButton);
        _toolbar.Dock = DockStyle.Top;
        _toolbar.FlowDirection = FlowDirection.LeftToRight;
        _toolbar.Name = "_toolbar";
        _toolbar.Padding = new Padding(8);
        _toolbar.WrapContents = false;
        //
        // ActivityLogView
        //
        Controls.Add(_gridHost);
        Controls.Add(_toolbar);
        Dock = DockStyle.Fill;
        Name = "ActivityLogView";
        AppearanceManager.Changed += AppearanceManager_Changed;
        Load += ActivityLogView_Load;
        ((System.ComponentModel.ISupportInitialize)_searchEdit.Properties).EndInit();
        ((System.ComponentModel.ISupportInitialize)_grid).EndInit();
        ((System.ComponentModel.ISupportInitialize)_gridView).EndInit();
        ((System.ComponentModel.ISupportInitialize)_gridHost).EndInit();
        _gridHost.ResumeLayout(false);
        ResumeLayout(false);
        PerformLayout();
    }

    #endregion

    private TextEdit _searchEdit;
    private SimpleButton _refreshButton;
    private GridControl _grid;
    private GridView _gridView;
    private LabelControl _emptyStateLabel;
    private PanelControl _gridHost;
    private FlowLayoutPanel _toolbar;
    private GridColumn _columnOccurredAtUtc;
    private GridColumn _columnPerformedBy;
    private GridColumn _columnMachineName;
    private GridColumn _columnAction;
    private GridColumn _columnDetails;
}
