using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace Clovent.Restaurant.Continuity;

/// <summary>Status of an emergency offline transaction during database reconciliation.</summary>
public enum ReconciliationStatus
{
    /// <summary>Recorded offline and awaiting replay to primary database.</summary>
    PendingReplay = 0,

    /// <summary>Successfully replayed and committed into primary database.</summary>
    Replayed = 1,

    /// <summary>Transaction already existed in primary database; duplicate safely ignored.</summary>
    DuplicateIgnored = 2,

    /// <summary>Data conflict encountered during replay requiring manager review.</summary>
    Conflict = 3,

    /// <summary>Replay failed due to unrecoverable validation error.</summary>
    Failed = 4,

    /// <summary>Marked for administrative / managerial manual review.</summary>
    RequiresManagerReview = 5
}

/// <summary>Line item snapshot in an emergency transaction.</summary>
public sealed record EmergencyTransactionLine(
    Guid ProductVariantId,
    string Sku,
    string Name,
    decimal Quantity,
    decimal UnitPrice,
    decimal LineTotal,
    string? Notes,
    decimal TaxRatePercentage = 0m,
    decimal TaxAmount = 0m,
    bool TaxIsInclusive = false,
    decimal DiscountAmount = 0m,
    string? ItemType = "Prepared");

/// <summary>Order snapshot captured during continuity mode.</summary>
public sealed record EmergencyOrderSnapshot(
    string OrderType,
    Guid? TableId,
    string? TableCode,
    IReadOnlyList<EmergencyTransactionLine> Lines,
    decimal Subtotal,
    decimal TaxTotal,
    decimal DiscountTotal,
    decimal ServiceChargeTotal,
    decimal GrandTotal,
    string? Notes,
    string? CustomerNotes,
    decimal RoundingAmount = 0m,
    string? Currency = "PKR",
    string? CacheVersion = null);

/// <summary>
/// Immutable, tamper-evident emergency transaction recorded locally when the
/// primary database or network connection is unavailable.
/// </summary>
public sealed class EmergencyTransaction
{
    /// <summary>Unique immutable identity for this transaction.</summary>
    public Guid TransactionId { get; init; } = Guid.NewGuid();

    /// <summary>Sequential sequence number generated by this terminal.</summary>
    public long SequenceNumber { get; init; }

    /// <summary>Human-readable collision-free local receipt number (e.g. CONT-POS01-00042).</summary>
    public string? LocalReceiptNumber { get; init; }

    /// <summary>Cache version token active when this transaction was priced and completed.</summary>
    public string? CacheVersion { get; init; }

    /// <summary>UTC timestamp when the transaction was completed offline.</summary>
    public DateTimeOffset TimestampUtc { get; init; } = DateTimeOffset.UtcNow;

    /// <summary>Terminal identity that originated the sale.</summary>
    public string TerminalId { get; init; } = Environment.MachineName;

    /// <summary>Branch identity the terminal belongs to.</summary>
    public Guid BranchId { get; init; }

    /// <summary>Warehouse stock identity associated with the terminal.</summary>
    public Guid WarehouseId { get; init; }

    /// <summary>Identity of the cashier logged in at the terminal.</summary>
    public Guid CashierId { get; init; }

    /// <summary>Display name of the cashier.</summary>
    public string CashierName { get; init; } = string.Empty;

    /// <summary>Order snapshot containing lines and financial totals.</summary>
    public EmergencyOrderSnapshot OrderSnapshot { get; init; } = null!;

    /// <summary>Tender method used (Only Cash is permitted offline by default).</summary>
    public string PaymentType { get; init; } = "Cash";

    /// <summary>Amount tendered by the customer.</summary>
    public decimal AmountTendered { get; init; }

    /// <summary>Change returned to the customer.</summary>
    public decimal ChangeGiven { get; init; }

    /// <summary>Current reconciliation state.</summary>
    public ReconciliationStatus ReconciliationStatus { get; set; } = ReconciliationStatus.PendingReplay;

    /// <summary>Reconciliation details, error, or confirmation notes.</summary>
    public string? ReconciliationDetails { get; set; }

    /// <summary>Timestamp when reconciliation completed, if replayed.</summary>
    public DateTimeOffset? ReconciledAtUtc { get; set; }

    /// <summary>Fixed genesis hash representing the null predecessor for the initial offline transaction.</summary>
    public const string GenesisHash = "0000000000000000000000000000000000000000000000000000000000000000";

    private static readonly byte[] MachineIntegrityKey = "Clovent-CBOS-Continuity-HMAC-MachineKey-v1-Production"u8.ToArray();

    /// <summary>Cryptographic hash or HMAC signature of the immediately preceding transaction in the journal chain.</summary>
    public string PreviousTransactionHash { get; init; } = GenesisHash;

    /// <summary>Keyed HMAC-SHA256 signature providing cryptographic tamper authentication.</summary>
    public string HmacSignature { get; init; } = string.Empty;

    /// <summary>SHA-256 checksum verifying journal integrity against serialization corruption.</summary>
    public string Checksum { get; init; } = string.Empty;

    /// <summary>Computes an integrity checksum over the immutable transaction properties for corruption detection.</summary>
    public static string ComputeChecksum(
        Guid transactionId,
        long sequenceNumber,
        DateTimeOffset timestampUtc,
        string terminalId,
        Guid branchId,
        Guid warehouseId,
        string cashierName,
        decimal grandTotal,
        string paymentType)
    {
        var raw = $"{transactionId:N}:{sequenceNumber}:{timestampUtc.ToUnixTimeMilliseconds()}:{terminalId}:{branchId:N}:{warehouseId:N}:{cashierName}:{grandTotal:F2}:{paymentType}";
        var hash = SHA256.HashData(Encoding.UTF8.GetBytes(raw));
        return Convert.ToHexString(hash);
    }

    /// <summary>Computes a keyed HMAC-SHA256 cryptographic signature verifying journal authenticity and hash chaining.</summary>
    public static string ComputeHmacSignature(
        Guid transactionId,
        long sequenceNumber,
        string previousTransactionHash,
        DateTimeOffset timestampUtc,
        string terminalId,
        Guid branchId,
        Guid warehouseId,
        string cashierName,
        decimal grandTotal,
        string paymentType)
    {
        var prevHash = string.IsNullOrWhiteSpace(previousTransactionHash) ? GenesisHash : previousTransactionHash;
        var raw = $"{transactionId:N}:{sequenceNumber}:{prevHash}:{timestampUtc.ToUnixTimeMilliseconds()}:{terminalId}:{branchId:N}:{warehouseId:N}:{cashierName}:{grandTotal:F2}:{paymentType}";
        var hash = HMACSHA256.HashData(MachineIntegrityKey, Encoding.UTF8.GetBytes(raw));
        return Convert.ToHexString(hash);
    }

    /// <summary>Validates the corruption-detection checksum of this transaction.</summary>
    public bool VerifyChecksum()
    {
        if (OrderSnapshot == null) return false;
        var expected = ComputeChecksum(
            TransactionId,
            SequenceNumber,
            TimestampUtc,
            TerminalId,
            BranchId,
            WarehouseId,
            CashierName,
            OrderSnapshot.GrandTotal,
            PaymentType);
        return string.Equals(Checksum, expected, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>Validates the keyed HMAC-SHA256 cryptographic signature of this transaction.</summary>
    public bool VerifyHmacSignature()
    {
        if (OrderSnapshot == null) return false;
        var expected = ComputeHmacSignature(
            TransactionId,
            SequenceNumber,
            PreviousTransactionHash,
            TimestampUtc,
            TerminalId,
            BranchId,
            WarehouseId,
            CashierName,
            OrderSnapshot.GrandTotal,
            PaymentType);
        return string.Equals(HmacSignature, expected, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Validates the complete cryptographic journal chain across a series of emergency transactions.
    /// Detects modification, reordering, truncation/gaps, duplicate replay, and broken hash chains.
    /// </summary>
    public static void ValidateChain(IReadOnlyList<EmergencyTransaction> transactions)
    {
        ArgumentNullException.ThrowIfNull(transactions);
        if (transactions.Count == 0) return;

        var seenIds = new HashSet<Guid>();
        for (int i = 0; i < transactions.Count; i++)
        {
            var tx = transactions[i];

            if (!seenIds.Add(tx.TransactionId))
            {
                throw new ContinuityTamperException($"Duplicate transaction identity {tx.TransactionId} detected in journal.");
            }

            if (!tx.VerifyChecksum())
            {
                throw new ContinuityTamperException($"Payload corruption detected: checksum failed for transaction {tx.TransactionId} at index {i}.");
            }

            if (!string.IsNullOrEmpty(tx.HmacSignature) && !tx.VerifyHmacSignature())
            {
                throw new ContinuityTamperException($"Cryptographic signature invalid: HMAC authentication failed for transaction {tx.TransactionId} at index {i}.");
            }

            if (i > 0)
            {
                var prev = transactions[i - 1];
                if (tx.SequenceNumber != prev.SequenceNumber + 1)
                {
                    throw new ContinuityTamperException(
                        $"Journal sequence violation at index {i}: expected sequence {prev.SequenceNumber + 1}, found {tx.SequenceNumber}. Reordering or truncation detected.");
                }

                var expectedPrevHash = !string.IsNullOrEmpty(prev.HmacSignature) ? prev.HmacSignature : prev.Checksum;
                if (!string.Equals(tx.PreviousTransactionHash, expectedPrevHash, StringComparison.OrdinalIgnoreCase))
                {
                    throw new ContinuityTamperException(
                        $"Broken hash chain at index {i}: previous hash does not match signature of transaction {prev.TransactionId}.");
                }
            }
        }
    }
}
