using System;

namespace Clovent.Inventory.Application.Forecasting.Dtos;

/// <summary>
/// Actionable purchase reorder recommendation generated by the predictive depletion engine.
/// </summary>
public sealed record ReorderRecommendationDto(
    Guid ProductVariantId,
    string Sku,
    string ItemName,
    Guid WarehouseId,
    decimal CurrentAvailable,
    decimal SuggestedReorderQuantity,
    decimal ProjectedDepletionHours,
    DateTimeOffset RecommendedOrderBeforeUtc,
    DateTimeOffset ScheduledGrnArrivalUtc,
    string Priority, // Emergency, High, Standard
    string Justification);
