SET NOCOUNT ON;
SELECT p.Code FROM [Identity].Permissions p WHERE p.Code LIKE 'feature.pos.%' ORDER BY p.Code;
SELECT 'TOTAL_PERMS', COUNT(*) FROM [Identity].Permissions;
SELECT 'ROLE_COLS', COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='Identity' AND TABLE_NAME='Roles';
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='Identity' AND TABLE_NAME='Roles' AND COLUMN_NAME LIKE '%erm%';
